#set the port
server:
  port: 9001
  servlet:
    context-path: /mytrans

#set up the database
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 123456

#configure mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  #open logs
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
